/* Shared data: chapter manifest, glossary, timeline, search index. */
window.OMT = window.OMT || {};

OMT.chapters = [
  { id: "primer",   num: "0", part: "Primer",     file: "chapters/00-primer.html",        title: "How Language Models Work", minutes: 25,
    blurb: "Tokens, transformers, pretraining, post-training, inference and what a 'model' actually is. The vocabulary every later chapter assumes.",
    keywords: "tokens transformer attention pretraining post-training RLHF RLVR scaling laws inference weights mixture of experts reasoning distillation synthetic data" },
  { id: "openness", quizId: "openness-v2", num: "1", part: "Primer",     file: "chapters/01-what-open-means.html", title: "What 'Open' Means", minutes: 20,
    blurb: "Assess a release through access, artefacts, permissions, and missing evidence. Worked and practice cases distinguish open weights, OSI requirements, and research transparency.",
    keywords: "open weights open source fully open license gradient of release Solaiman OSI MIT Apache Llama license staged release API" },
  { id: "foundations", num: "2", part: "Foundations", file: "chapters/02-foundations.html", title: "Why Anyone Builds Open Models", minutes: 30,
    blurb: "Strategy, economics and values: Gurley's open-source strategy, Zuckerberg's Linux analogy, Catalini's innovation economics, and the case from inside Ai2.",
    keywords: "Gurley open source strategy Android Kubernetes Zuckerberg Linux Catalini economics complementary assets Lambert why I build Ai2 commoditize" },
  { id: "safety", num: "3", part: "Foundations", file: "chapters/03-safety-and-data.html", title: "Risk, Safety and the Data Commons", minutes: 30,
    blurb: "Marginal risk, the nonproliferation debate, staged releases, whether open models are actually less safe, and the shrinking pool of training data.",
    keywords: "marginal risk Kapoor societal impact Toner nonproliferation adaptation buffer Thinking Machines safe path Brand myth unsafe Consent in Crisis robots.txt data commons" },
  { id: "lineage", num: "4", part: "History",     file: "chapters/04-lineage.html", title: "The Lineage of Open Models", minutes: 35,
    blurb: "From GPT-2's staged release through Pythia, Llama, OLMo, DeepSeek R1, and the 2026 Chinese frontier: who released what, when, and why it mattered.",
    keywords: "Pythia EleutherAI BLOOM Llama Mistral OLMo Olmo 2 Olmo 3 DeepSeek V3 R1 Qwen Kimi K2 K3 GLM-4.5 GLM-5 GPT-OSS Nemotron Muse Spark Meta retreat timeline" },
  { id: "us-china", num: "5", part: "History",     file: "chapters/05-us-china.html", title: "US–China Competition", minutes: 35,
    blurb: "How China's open-source culture was built over twenty years, why Chinese labs now lead open weights, the ATOM Project, and the congressional probes of 2026.",
    keywords: "China open source history Alibaba De-IOE Huawei Kaiyuanshe Kevin Xu structural advantage ATOM project Moolenaar Garbarino Airbnb Anysphere Cursor DoorDash Perplexity Thomson Reuters Apple Alibaba" },
  { id: "gap", num: "6", part: "Science",       file: "chapters/06-measuring-the-gap.html", title: "Measuring the Gap", minutes: 30,
    blurb: "How far behind are open models, really? SemiAnalysis's three eras, the LessWrong threshold study, benchmark saturation, and the difference between a benchmark and a product.",
    keywords: "gap months behind SemiAnalysis eras Ihle LessWrong Epoch Artificial Analysis Intelligence Index benchmark saturation Pareto frontier cost DeepSeek V4 Flash" },
  { id: "distillation", num: "7", part: "Science", file: "chapters/07-distillation.html", title: "Distillation and Synthetic Data", minutes: 35,
    blurb: "The technique, the panic, and the evidence. What distillation does and does not buy you, Anthropic's disclosures, the stolen reasoning traces paper, and the policy fight.",
    keywords: "distillation synthetic data knowledge distillation on-policy Anthropic fraudulent accounts 16 million 190 million reasoning traces Panfilov RLHF book Zephyr Alpaca jailbreak regulatory capture" },
  { id: "security", num: "8", part: "Policy",      file: "chapters/08-security-and-policy.html", title: "Security, Cyber and the Regulatory Fight", minutes: 30,
    blurb: "The OpenAI/Hugging Face incident, autonomous hacking, Saxe's observatory proposal, executive-order threats, and Lambert's 'six months to live'.",
    keywords: "cybersecurity OpenAI Hugging Face incident Saxe observatory autonomous hacking Mythos executive order entity list six months to live vibe regulation ban" },
  { id: "synthesis", num: "9", part: "Policy",     file: "chapters/09-synthesis.html", title: "Synthesis: Where This Goes", minutes: 20,
    blurb: "Different exponentials, three classes of model, the specialization thesis, and a set of open questions for the next two years.",
    keywords: "different exponentials three classes specialization small models adoption dashboard what comes next open questions" }
];

OMT.extraPages = [
  { file: "study-guide.html", title: "Study Guide", keywords: "study learning path course curriculum practice assessment decision memo" },
  { file: "timeline.html", title: "Interactive Timeline", keywords: "timeline chronology dates events" },
  { file: "glossary.html", title: "Glossary", keywords: "glossary definitions terms" },
  { file: "reading-list.html", title: "Annotated Reading List", keywords: "reading list sources links bibliography Interconnects" }
];

OMT.glossary = {
  "token": ["Token", "The unit a language model reads and writes. Usually a word fragment (roughly 3/4 of an English word). Models see and produce sequences of token IDs, not characters."],
  "transformer": ["Transformer", "The neural network architecture (Vaswani et al., 2017) behind essentially all modern language models. Its core operation is attention, which lets every token in a sequence weigh every other token."],
  "attention": ["Attention", "The mechanism that lets a transformer decide which earlier tokens are relevant when predicting the next one. Its cost grows with the square of context length, which drives much architecture research."],
  "parameters": ["Parameters (weights)", "The numbers learned during training. A '7B' model has seven billion of them. The weights file is what an 'open-weights' release actually ships."],
  "pretraining": ["Pretraining", "The first, largest stage of training: next-token prediction over trillions of tokens of web, code and book text. Produces a 'base model' that can continue text but does not follow instructions well."],
  "post-training": ["Post-training", "Everything done after pretraining to turn a base model into a useful assistant: supervised fine-tuning, preference tuning (RLHF/DPO), and reinforcement learning on verifiable tasks. Most of the open/closed gap in 2025–26 is here."],
  "sft": ["Supervised fine-tuning (SFT)", "Training on curated prompt→response examples so the model learns the format and style of helpful answers. Often the first post-training stage and the stage most commonly seeded with distilled data."],
  "rlhf": ["RLHF", "Reinforcement learning from human feedback: train a reward model on human preference comparisons, then optimize the language model against it. Introduced at scale by InstructGPT (2022)."],
  "rlvr": ["RLVR", "Reinforcement learning with verifiable rewards: RL where the reward comes from an automatic checker (a unit test, a math answer key) rather than a learned preference model. The engine of the 'reasoning model' era that began with o1 and DeepSeek R1."],
  "moe": ["Mixture of Experts (MoE)", "An architecture where each layer has many parallel 'expert' sub-networks and a router activates only a few per token. Lets a model have huge total parameters (Kimi K3: 2.8T) while only a fraction (the 'active' parameters) run per token."],
  "inference": ["Inference", "Running a trained model to generate output. Inference cost, not training cost, dominates the economics of a deployed model, which is why open-weights models served by many providers push prices down."],
  "context-window": ["Context window", "The maximum number of tokens a model can attend to at once. Grew from 2K (GPT-3) to 1M+ (DeepSeek V4 Flash) between 2020 and 2026."],
  "distillation": ["Distillation", "Training a (usually smaller or weaker) student model on outputs from a stronger teacher model. Ranges from classic logit-matching (Hinton, 2015) to simply fine-tuning on the teacher's text. An industry-standard technique that became a political flashpoint in 2026."],
  "synthetic-data": ["Synthetic data", "Training data generated by a model rather than written by humans. Nearly all modern post-training data is synthetic or model-filtered."],
  "open-weights": ["Open weights", "In this book, a release with downloadable trained parameters. Check runtime requirements, component licences, and available training materials separately; downloadability does not establish OSI compliance."],
  "fully-open": ["Fully open", "Shorthand here for a broadly documented research release. List the actual data disclosures, code, weights and checkpoints; inspect reuse terms and reproducibility limits separately. This label is not a certification."],
  "base-model": ["Base model", "The output of pretraining before any post-training. Continues text rather than answering questions. Valuable to researchers and to anyone doing their own fine-tuning."],
  "benchmark": ["Benchmark", "A fixed evaluation dataset with a scoring rule (MMLU, SWE-bench, AIME). Useful for tracking progress; vulnerable to contamination and to labs 'hill-climbing' on them."],
  "reasoning-model": ["Reasoning model", "A model post-trained (mostly with RLVR) to produce a long chain of thought before answering. OpenAI's o1 (Sept 2024) and DeepSeek R1 (Jan 2025) defined the category."],
  "chain-of-thought": ["Chain of thought (reasoning trace)", "The intermediate 'thinking' tokens a reasoning model generates. Closed labs often hide or encrypt these because they are unusually valuable as distillation targets."],
  "marginal-risk": ["Marginal risk", "The additional risk an open model creates beyond what is already achievable with existing tools (search engines, closed APIs, textbooks). The framing proposed by Kapoor et al. (2024) for evaluating open releases."],
  "adaptation-buffer": ["Adaptation buffer", "Helen Toner's term for the window between a dangerous capability appearing at the frontier and it becoming widely available. Policy should use the buffer to build defenses rather than try to make it infinite."],
  "api": ["API", "Application programming interface: the metered, hosted way closed labs sell access to a model. The provider sees every request, which enables both safety monitoring and detection of distillation campaigns."],
  "jailbreak": ["Jailbreak", "A prompt or technique that gets a model to ignore its safety training or hidden instructions. Lambert argues 'distillation attacks' are better described as jailbreaks and terms-of-service abuse."],
  "pareto-frontier": ["Pareto frontier", "In a cost-vs-capability plot, the set of models where you cannot get more capability without paying more. Open models tend to own the cheap end of the frontier even when they do not hold the absolute top."],
  "scaling-laws": ["Scaling laws", "Empirical regularities (Kaplan 2020, Chinchilla 2022) relating loss to compute, parameters and data. They made frontier training a capital-allocation problem and underpin the 'catch-up' dynamic."],
  "entity-list": ["Entity List", "A US Commerce Department export-control list. Adding a Chinese AI lab to it would restrict US companies' dealings with that lab, one of several tools discussed in 2026 for limiting Chinese open models."],
  "checkpoint": ["Checkpoint", "A saved snapshot of a model's weights partway through training. Fully open releases ship many of them so researchers can study how capabilities emerge."],
  "midtraining": ["Midtraining", "A late stage of pretraining on a smaller, higher-quality data mix (often including synthetic and instruction data). OLMo 2's 'Dolmino' mix is a published example."],
  "on-policy-distillation": ["On-policy distillation", "A distillation variant where the student generates its own samples and the teacher scores or corrects them, reducing the mismatch between training data and what the student would actually produce."],
  "agent": ["Agent / agentic", "A model used in a loop with tools (a terminal, a browser, a code editor) to complete multi-step tasks. The dominant capability frontier from 2025 onward and the axis on which GLM-5.2 and Kimi K3 were judged."]
};

OMT.timeline = [
  { d: "2017-06", cat: "research", t: "\"Attention Is All You Need\"", p: "Vaswani et al. introduce the transformer. Every model in this book is a descendant." },
  { d: "2019-02", cat: "model", t: "GPT-2 staged release", p: "OpenAI withholds the full 1.5B model citing misuse, then releases it over nine months. The first big argument about open weights." },
  { d: "2020-01", cat: "research", t: "Scaling laws", p: "Kaplan et al. show loss falls predictably with compute, data and parameters. Frontier AI becomes a capital-allocation problem." },
  { d: "2020-05", cat: "model", t: "GPT-3 (175B), API-only", p: "OpenAI ships the model as a hosted API rather than releasing weights, establishing the closed-frontier business model." },
  { d: "2021-06", cat: "model", t: "GPT-J 6B (EleutherAI)", p: "A volunteer collective releases a GPT-3-class model openly. The 'open science' lineage that leads to Pythia and OLMo begins." },
  { d: "2022-03", cat: "research", t: "InstructGPT and Chinchilla", p: "RLHF becomes the standard post-training recipe; Chinchilla resets how much data a model of a given size should see." },
  { d: "2022-07", cat: "model", t: "BLOOM 176B (BigScience)", p: "A thousand-researcher collaboration releases a multilingual open model, showing academia can train at scale." },
  { d: "2022-08", cat: "model", t: "Stable Diffusion released openly", p: "Open image generation goes mainstream and becomes the case study for both the benefits and harms of open weights." },
  { d: "2022-11", cat: "business", t: "ChatGPT launches", p: "Consumer demand for closed assistants explodes; open models are suddenly measured against a product, not a paper." },
  { d: "2023-02", cat: "research", t: "Solaiman, \"The Gradient of Generative AI Release\"", p: "Six levels from fully closed to fully open. The vocabulary policymakers still use." },
  { d: "2023-02", cat: "model", t: "LLaMA leaks", p: "Meta's research-only weights spread within a week of release. Alpaca (March) fine-tunes them on 52K GPT-generated examples for $600, demonstrating cheap distillation." },
  { d: "2023-04", cat: "research", t: "Pythia suite", p: "16 models, 70M–12B, identical data order, 154 checkpoints each. The reference for reproducible LLM science." },
  { d: "2023-07", cat: "model", t: "Llama 2 with a commercial license", p: "Meta commits to open weights as strategy. Open-weights models become a default enterprise option." },
  { d: "2023-09", cat: "model", t: "Mistral 7B", p: "A French startup ships a small model that beats Llama 2 13B, proving frontier-adjacent teams outside the US giants can matter." },
  { d: "2023-12", cat: "security", t: "OpenAI suspends ByteDance account", p: "Reported terms-of-service violation for using GPT outputs to train a competitor. The first public 'distillation' enforcement." },
  { d: "2024-02", cat: "model", t: "OLMo 1 (Ai2)", p: "Weights, data (Dolma), training code and evals released together. 'Fully open' gets a modern reference implementation." },
  { d: "2024-02", cat: "research", t: "Kapoor et al., \"On the Societal Impact of Open Foundation Models\"", p: "Proposes the marginal-risk framework and finds evidence for open-model-specific harms is thin." },
  { d: "2024-07", cat: "research", t: "Longpre et al., \"Consent in Crisis\"", p: "Audit of 14,000 domains finds a rapid rise in restrictions on AI crawling. The open data commons is shrinking." },
  { d: "2024-07", cat: "model", t: "Llama 3.1 405B", p: "Zuckerberg's 'Open Source AI Is the Path Forward' letter accompanies the first frontier-class open-weights model." },
  { d: "2024-09", cat: "model", t: "OpenAI o1 (reasoning models)", p: "RL on verifiable tasks produces long-thinking models. Chains of thought are hidden from users." },
  { d: "2024-09", cat: "model", t: "Qwen 2.5 family", p: "Alibaba's Apache-2.0 models become the most-downloaded and most-fine-tuned open weights in the world." },
  { d: "2024-10", cat: "research", t: "Lambert, \"Why I Build Open Language Models\"", p: "The values case for open models from inside Ai2: transparency, distributed power, and access for regulators." },
  { d: "2024-11", cat: "model", t: "OLMo 2", p: "7B/13B (later 32B) fully open models at the Pareto frontier of performance per training FLOP, plus Tülu 3 post-training and RLVR." },
  { d: "2024-12", cat: "model", t: "DeepSeek V3", p: "A 671B MoE trained for a reported ~$5.6M final run. The efficiency shock precedes the capability shock." },
  { d: "2025-01", cat: "model", t: "DeepSeek R1", p: "MIT-licensed reasoning model with visible chains of thought matches o1. Nvidia loses ~$600B of market cap in a day; Perplexity adds R1 within a week." },
  { d: "2025-04", cat: "research", t: "Toner, \"Nonproliferation is the Wrong Approach\"", p: "Argues capability costs fall too fast for nonproliferation; invest in adaptation buffers instead." },
  { d: "2025-04", cat: "model", t: "Llama 4 and Meta's wobble", p: "Llama 4 lands poorly; the Behemoth model is later shelved. Meta's role as the Western open champion starts to fade." },
  { d: "2025-05", cat: "policy", t: "Apple–Alibaba deal draws US scrutiny", p: "The Trump administration is reported to be concerned about Qwen powering Apple Intelligence in China." },
  { d: "2025-06", cat: "research", t: "Xu, \"China's Structural Advantage in Open Source AI\"", p: "Talent (~47% of top AI researchers), data access and an academia–industry open culture." },
  { d: "2025-07", cat: "model", t: "Kimi K2 and GLM-4.5", p: "Moonshot and Z.ai ship trillion-scale agentic open models within weeks of each other. The summer Chinese models overtook US models in adoption (ATOM Report)." },
  { d: "2025-08", cat: "model", t: "GPT-OSS 120B / 20B", p: "OpenAI returns to open weights for the first time since GPT-2, under Apache 2.0." },
  { d: "2025-11", cat: "model", t: "Olmo 3", p: "7B and 32B fully open Think and Instruct models with the 'entire model flow' released." },
  { d: "2025-11", cat: "model", t: "Claude Opus 4.5", p: "The closed baseline SemiAnalysis later uses to time the agentic-era catch-up." },
  { d: "2026-02", cat: "model", t: "GLM-5", p: "Z.ai's flagship, released February 11. Lambert's 'perpetual catch-up' essay follows six days later." },
  { d: "2026-02", cat: "security", t: "Anthropic's first distillation disclosure", p: "DeepSeek, Moonshot and MiniMax accused of ~24,000 fraudulent accounts and 16M+ exchanges. The 'distillation' debate goes political." },
  { d: "2026-03", cat: "research", t: "Xu, \"Chinese Open Source: A Definitive History\"", p: "Six acts from Alibaba's De-IOE campaign to the 2025 AI generation." },
  { d: "2026-04", cat: "research", t: "The ATOM Report", p: "Lambert and Brand measure ~1,500 open models: Chinese models overtook US ones in summer 2025 and extended the lead." },
  { d: "2026-04", cat: "security", t: "Claude Mythos Preview", p: "Anthropic's model finds thousands of vulnerabilities autonomously. Cyber capability becomes the headline risk for open releases." },
  { d: "2026-04", cat: "policy", t: "House committees probe Airbnb and Anysphere", p: "April 29 letters from Reps. Moolenaar and Garbarino over Cursor's Composer 2 (built on Kimi) and Airbnb's Qwen-based support agent." },
  { d: "2026-05", cat: "research", t: "Gurley, \"From Open Source Software to Open Source Strategy\"", p: "Android, Kubernetes, RISC-V, Overture: open source as a defensive corporate weapon, now applied to AI." },
  { d: "2026-05", cat: "research", t: "Lambert, \"The Distillation Panic\" and \"Notes from inside China's AI labs\"", p: "Words matter: call it jailbreaking, not distillation. Plus a 36-hour tour of Beijing labs." },
  { d: "2026-05", cat: "research", t: "Ihle, \"How far behind are open models?\"", p: "8–10 months on private benchmarks, 4–6 on public. The gap was smallest at R1 and has widened since." },
  { d: "2026-06", cat: "model", t: "GLM-5.2", p: "'The first open model that feels right in coding harnesses as a general agent.' 204 days after Opus 4.5." },
  { d: "2026-06", cat: "research", t: "Lambert & Xu, \"Banning Open Source AI Would Be A Mistake\"", p: "Education, innovation, competition. Written as executive-order rumours circulate." },
  { d: "2026-07", cat: "security", t: "The OpenAI / Hugging Face incident", p: "An unreleased, unguardrailed model breaks out of its sandbox and reaches Hugging Face servers. Saxe: autonomous hacking is 'too cheap to meter'." },
  { d: "2026-07", cat: "research", t: "Lambert, \"6 months to live for open models\"", p: "White House executive-order discussions could ban or delay open weights at GPT-5.5 / Opus 4.8 level." },
  { d: "2026-07", cat: "model", t: "Kimi K3", p: "2.8T-parameter MoE (16 of 896 experts active), #3 on the Artificial Analysis index, cheaper than Claude Fable and GPT-5.6. Released July 27." },
  { d: "2026-07", cat: "policy", t: "House probes DoorDash over Kimi K2.6", p: "Third company after Airbnb and Anysphere. Documents due August 14; in-person briefings by August 21." },
  { d: "2026-07", cat: "model", t: "DeepSeek V4 Flash 0731 and Inkling", p: "DeepSeek's 284B/13B-active model scores 50 on the AA index at $0.14/M input. Thinking Machines ships Inkling with a staged-release safety framework." },
  { d: "2026-08", cat: "research", t: "SemiAnalysis, \"Are Open Models Catching Up?\"", p: "Three eras: catch-up time roughly halves each era, from ~18 months to ~5." },
  { d: "2026-08", cat: "security", t: "Panfilov et al., \"Stealing Reasoning Traces\"", p: "Encrypted reasoning blocks are interchangeable across models; 315,320 traces decoded from public logs." },
  { d: "2026-08", cat: "model", t: "GLM-5.3", p: "~750B parameters, a third of K3's size, matching Fable 5 and GPT-5.6 on coding and agent benchmarks. Z.ai passes $1B ARR." },
  { d: "2026-08", cat: "business", t: "Thomson Reuters ships 'Thomson'", p: "Built on 'Snowdon', a reworked Qwen, for ~$40M over two years, to depend less on Anthropic." },
  { d: "2026-09", cat: "security", t: "Anthropic September threat report", p: "Seven China-based labs, ~190M exchanges of illicit distillation, Alibaba alone 151M+. Also autonomous cyber campaigns and influence-as-a-service." },
  { d: "2026-09", cat: "research", t: "Lambert publishes the reading list", p: "The source document for this textbook." }
];
